### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by weswhet** [grahamgilbert/crypt#101]
Time to move to py3, as Snow Catalina is around the corner. 

- [x] Convert code to py3
- [x] Bundle own py3 framework with `pyobjc`
- [x] Sunset FoundationPlist, replace with plistlib in py3 (pour one out)
- [x] Update make file for latest py3
- [x] Update any build scripts
- [x] Update Pre/Postinstall scripts if necessary
- [x] Move auth plugin to latest swift
- [x] Optional - Add `black`, `isort`, `pylint`, to a `pre-commit`

**Comment by grahamgilbert** [comment]
I'd rather just use a github action than pre commit. I personally don't like it much. This sort of things should be in CI, not on developer workstations.

**Comment by weswhet** [comment]
agreed, was thinking about making it optional so if you want to run/simulate what the CI would run you can.

**Comment by grahamgilbert** [comment]
Put it all in a script or makefile and then CI can call that.

**Comment by erikng** [comment]
If you bundle your own python, can you do what Munki did where the shebangs point to a symbolic link and people can override that symbolic link? Otherwise we now have yet another python3 on the machines.

Other alternatives are available but I don't want to spam them here and Graham is aware of them.

**Comment by grahamgilbert** [comment]
I’m not hard up for a few mb of disk space. I’m completely indifferent to this. Imo switching to python 3 is a stop gap before moving to a swift binary.

**Comment by erikng** [comment]
Agreed on the swift part.

**Comment by arubdesu** [comment]
Maybe we should rename this 'update checkin for macOS 11' and leave the prescriptive-ness of even py3 out of it? (I totally did benefit from being able to ship a forked version of the existing python checkin that doesn't get tripped up on a weird path incompatibility in AWS's API Gateway product, but) maybe this should be separated out into golang for the communication part and python for the platform-specific stuffs? May make sense as many envs are already leveraging the shared backend for at least Ubuntu in the time since Square open sourced their luks2crypt thingy.
