### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/crypt#89]
Basic auth on the client side has been requested https://github.com/grahamgilbert/Crypt-Server/issues/60#issuecomment-441577233

**Comment by weswhet** [comment]
This can be implemented with the new `AdditionalCurlOpts` preference. If this doesn't suffice then we can reopen.

**Comment by fortiko** [comment]
Great project! Just in case it saves somebody else some time for http auth with cURL:

Only after manually adding some debug statements in `checkin`, I got the following error message that clarified my issue:

`curl: option --user USER:PASSWORD is unknown`

Weirdly enough, the same command edited for command line worked. Turns out that in order to use `AdditionalCurlOpts` in a mobileconfig file, one needs to specify the value pair for the `--user` setting in a separate entry as shown below, NOT in one entry together with "--user" as you would expect from the command line:

**WORKS**:
```
<key>AdditionalCurlOpts</key>
<array>
	<string>--user</string>
	<string>USER:PASSWORD</string>
	<string>--tlsv1.3</string>
</array>
```

does **NOT** work:
```
<key>AdditionalCurlOpts</key>
<array>
	<string>--user USER:PASSWORD</string>
	<string>--tlsv1.3</string>
</array>
```

This leads to my suggestion, perhaps writing the (already existing!) error and output redirects to the log in case of failure, like so:

```
    else:
        logging.error("Key escrow unsuccessful.")
        logging.debug(ouput)
        logging.debug(error)
        return False
